### ISSUE TITLE
No .pem files

### ISSUE THREAD

**Issue by sholtomaud** [BrianFarnhill/AWSDeveloperEnvironment#10]
We have enterprise requirements for SSO+SAML and no long-lived keys or .pem files.

Is there a way to accommodate these requirements in our `~/.ssh/config` and `~/.aws/config`?

If we do `aws configure sso` with a config file like that then it seems that the SSO+SAML requirement is met, however this `IdentityFile ~/.ssh/*.pem` is still a gotcha.

```sh
  [profile xyz] 
  sso_start_url = 
  sso_region = 
  sso_account_id = 
  sso_role_name = 
```

**Comment by BrianFarnhill** [comment]
From my testing, the SSH key (*.pem file) is still required when you SSH to an instance, the session manager connections don't work without it (you get authentication issues). You still need valid SSO creds to authenticate to session manager in the first place (especially since you can't SSH directly to the instance as it's in a private subnet), but to the best of my knowledge there's no way around the need for the PEM file.

**Comment by sholtomaud** [comment]
So, is there a best enterprise practice for handling PEM files when multiple users need to access the same ec2? 

Or is the assumption of this setup 1 PEM per user? And so only one ec2 per user?

**Comment by BrianFarnhill** [comment]
This specific repo is targeted more at a single instance per user (since they power off when not in use you're only paying as you go). That said, you could pretty easily store the PEM file in either secrets manager or parameter store (as a secure string) and have the AWS CLI pull it down locally when someone needs it. Then you have an audit trail of users who have copied the contents of the PEM file down.

**Comment by sholtomaud** [comment]
There's an idea.
